name: $(date:yyyyMMdd)$(rev:.rr)

pr:
  - master

trigger:
  - master

stages:
  - stage: build
    jobs:
      - job: build
        steps:
          - script: dotnet build
  - stage: test
    jobs:
      - job: tests
        steps:
          - script: dotnet test
  - stage: pack
    jobs:
      - job: pack_client
        steps:
          - task: Docker@2
            inputs:
              command: login
              containerRegistry: tylermart-acr
          - script: |
              docker image build --file TylerMart.Client/Dockerfile --tag $(AzureContainerRegistry)/tylermart-client:latest .
              docker image push $(AzureContainerRegistry)/tylermart-client:latest
          - task: Docker@2
            inputs:
              command: logout
              containerRegistry: tylermart-acr
      - job: pack_database
        steps:
          - task: Docker@2
            inputs:
              command: login
              containerRegistry: tylermart-acr
          - script: |
              docker image build --file TylerMart.Storage/Dockerfile --tag $(AzureContainerRegistry)/tylermart-database:latest .
              docker image push $(AzureContainerRegistry)/tylermart-database:latest
          - task: Docker@2
            inputs:
              command: logout
              containerRegistry: tylermart-acr
  - stage: deploy
    jobs:
      - job: deploy
        pool:
          vmImage: ubuntu-18.04
        steps:
          - task: AzureWebAppContainer@1
            displayName: Web App Container
            inputs:
              appName: tylermart-webapp
              azureSubscription: azure
              resourceGroupName: $(AzureResourceGroup)
              multicontainerConfigFile: docker-compose.yml
              deployToSlotOrASE: true
